# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 09:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0013_auto_20160801_1241'),
        ('acl', '0004_auto_20150806_1031'),
        ('users', '0015_auto_20160619_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('in_position_since', models.DateField(default=django.utils.timezone.now, verbose_name='In position since')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to='communities.Committee', verbose_name='Committee')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committee_members_invited', to=settings.AUTH_USER_MODEL, verbose_name='Invited by')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to='acl.Role', verbose_name='Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['committee'],
                'verbose_name': 'Committee Member',
                'verbose_name_plural': 'Committee Members',
            },
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Is community manager?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to='communities.Community', verbose_name='Community')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_members_invited', to=settings.AUTH_USER_MODEL, verbose_name='Invited by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['community'],
                'verbose_name': 'Community Member',
                'verbose_name_plural': 'Community Members',
            },
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='membership',
            name='community',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.AlterUniqueTogether(
            name='communitymembership',
            unique_together=set([('community', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='committeemembership',
            unique_together=set([('committee', 'user')]),
        ),
    ]
