# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-14 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_remove_meeting_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingparticipant',
            name='default_group_name',
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='group_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Group'),
        ),
    ]
