# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-27 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0015_auto_20160822_1626'),
        ('issues', '0009_auto_20151020_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IssueNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IssuesGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shultze_issues_graph', to='communities.Committee')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shultze_issues_graph', to='communities.Community')),
            ],
        ),
        migrations.AddField(
            model_name='issuenode',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='shultze.IssuesGraph'),
        ),
        migrations.AddField(
            model_name='issuenode',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shultze_graph_node', to='issues.Issue'),
        ),
        migrations.AddField(
            model_name='issueedge',
            name='from_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='shultze.IssueNode'),
        ),
        migrations.AddField(
            model_name='issueedge',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='shultze.IssuesGraph'),
        ),
        migrations.AddField(
            model_name='issueedge',
            name='to_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='shultze.IssueNode'),
        ),
    ]
